import { ScholarshipRow } from "@/types/database";
export type { ScholarshipRow };

export const SCHOLARSHIPS: ScholarshipRow[] = [
  {
    id: "sch-001",
    name: "HDFC Badhte Kadam Scholarship 2025",
    provider: "HDFC Bank Parivartan",
    provider_type: "Corporate",
    amount: 75000,
    deadline: "2025-08-31",
    course_levels: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 55,
    description:
      "HDFC Bank's flagship scholarship supporting meritorious students from economically weaker backgrounds pursuing undergraduate and postgraduate studies. Covers tuition fees, books, and living expenses.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 12 Marksheet", "College ID", "Bank Passbook"],
    apply_url: "https://www.hdfcbank.com/scholarships",
    is_featured: true,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Commerce", "Arts"],
    emoji: "🏦",
  },
  {
    id: "sch-002",
    name: "Tata Capital Pankh Scholarship",
    provider: "Tata Capital",
    provider_type: "Corporate",
    amount: 50000,
    deadline: "2025-10-10",
    course_levels: ["UG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 60,
    description:
      "Empowering students from disadvantaged backgrounds to soar higher with quality education. Annual scholarship covering up to ₹50,000 for undergraduate studies.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 12 Marksheet", "Bank Passbook"],
    apply_url: "https://tatacapital.com/pankh",
    is_featured: true,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Commerce", "Arts", "Law"],
    emoji: "🦋",
  },
  {
    id: "sch-003",
    name: "Kotak Kanya Scholarship",
    provider: "Kotak Education Foundation",
    provider_type: "Corporate",
    amount: 150000,
    deadline: "2025-11-30",
    course_levels: ["UG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Female"],
    states: [],
    religions: [],
    min_percentage: 75,
    description:
      "Exclusively for meritorious girl students from low-income families pursuing professional degree courses. One of the highest-value corporate scholarships for women in India.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 12 Marksheet", "College ID", "Bank Passbook", "Passport Photo"],
    apply_url: "https://kotakeducation.org/kanya",
    is_featured: true,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Law", "MBA"],
    emoji: "👩‍🎓",
  },
  {
    id: "sch-004",
    name: "Central Sector Scholarship Scheme",
    provider: "Ministry of Education, Govt. of India",
    provider_type: "Government",
    amount: 20000,
    deadline: "2025-09-15",
    course_levels: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 80,
    description:
      "Central government scholarship for top Class 12 board exam performers from low-income families. Available for students above 80th percentile in their respective boards.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 12 Marksheet", "Bank Passbook"],
    apply_url: "https://scholarships.gov.in",
    is_featured: true,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Commerce", "Arts", "Science"],
    emoji: "🏛️",
  },
  {
    id: "sch-005",
    name: "INSPIRE Scholarship for Higher Education (SHE)",
    provider: "Department of Science & Technology",
    provider_type: "Government",
    amount: 80000,
    deadline: "2025-12-15",
    course_levels: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 75,
    description:
      "For students pursuing BSc/Int. MSc in Natural & Basic Sciences. Attracts talented youth to pursue careers in research and innovation.",
    documents_required: ["Aadhaar Card", "Class 12 Marksheet", "College ID", "Bank Passbook"],
    apply_url: "https://online-inspire.gov.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Pure Sciences", "Research"],
    emoji: "🔬",
  },
  {
    id: "sch-006",
    name: "Aditya Birla Capital Scholarship",
    provider: "Aditya Birla Capital",
    provider_type: "Corporate",
    amount: 65000,
    deadline: "2025-09-30",
    course_levels: ["UG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 60,
    description:
      "Supporting meritorious and financially needy students in their pursuit of higher education. Covers undergraduate studies across all disciplines.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 12 Marksheet", "Bank Passbook", "College ID"],
    apply_url: "https://adityabirlacapital.com/scholarship",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Commerce", "Arts", "Science"],
    emoji: "🏢",
  },
  {
    id: "sch-007",
    name: "Post Matric Scholarship for OBC Students",
    provider: "Ministry of Social Justice, Govt. of India",
    provider_type: "Government",
    amount: 12000,
    deadline: "2025-09-30",
    course_levels: ["Class 11", "Class 12", "UG", "PG", "PhD"],
    categories: ["OBC"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: null,
    description:
      "National Scholarship Portal scheme for OBC students pursuing post-matric education. Covers maintenance allowance, study tour charges, and thesis/dissertation fees.",
    documents_required: ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Previous Marksheet", "Bank Passbook"],
    apply_url: "https://scholarships.gov.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Commerce", "Arts", "Science", "Law"],
    emoji: "🎖️",
  },
  {
    id: "sch-008",
    name: "Post Matric Scholarship for SC/ST Students",
    provider: "Ministry of Tribal Affairs, Govt. of India",
    provider_type: "Government",
    amount: 15000,
    deadline: "2025-10-31",
    course_levels: ["Class 11", "Class 12", "UG", "PG", "PhD"],
    categories: ["SC", "ST"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: null,
    description:
      "Comprehensive scholarship for SC/ST students at all post-matric levels. Covers tuition fees, maintenance allowance, and additional allowances for research scholars.",
    documents_required: ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Previous Marksheet", "Bank Passbook"],
    apply_url: "https://scholarships.gov.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Commerce", "Arts", "Science", "Law"],
    emoji: "🎖️",
  },
  {
    id: "sch-009",
    name: "Reliance Foundation Undergraduate Scholarship",
    provider: "Reliance Foundation",
    provider_type: "Corporate",
    amount: 200000,
    deadline: "2025-11-15",
    course_levels: ["UG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 60,
    description:
      "One of India's most prestigious corporate scholarships. Supports exceptional students in STEM and humanities with mentorship, networking, and up to ₹2,00,000 per year.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 12 Marksheet", "College ID", "Bank Passbook", "SOP / Essay"],
    apply_url: "https://reliancefoundation.org/scholarship",
    is_featured: true,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "STEM", "Arts", "Humanities"],
    emoji: "💎",
  },
  {
    id: "sch-010",
    name: "Swanath Scholarship Scheme (AICTE)",
    provider: "AICTE",
    provider_type: "Government",
    amount: 50000,
    deadline: "2025-09-30",
    course_levels: ["UG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: null,
    description:
      "For students who have lost their parents due to COVID-19, or whose parents are martyred defence/paramilitary personnel. Covers technical undergraduate and diploma programs.",
    documents_required: ["Aadhaar Card", "Death Certificate (Parent)", "College ID", "Bank Passbook"],
    apply_url: "https://aicte-india.org/swanath",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Technical"],
    emoji: "🛡️",
  },
  {
    id: "sch-011",
    name: "PM Scholarship Scheme for CRPF",
    provider: "Ministry of Home Affairs",
    provider_type: "Government",
    amount: 36000,
    deadline: "2025-10-31",
    course_levels: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 60,
    description:
      "For children and widows of CRPF personnel. Monthly stipend for professional degree/diploma courses — ₹3,000/month for boys and ₹3,600/month for girls.",
    documents_required: ["Aadhaar Card", "Service Certificate", "Class 12 Marksheet", "College ID", "Bank Passbook"],
    apply_url: "https://scholarships.gov.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Law", "MBA"],
    emoji: "🏅",
  },
  {
    id: "sch-012",
    name: "Begum Hazrat Mahal National Scholarship",
    provider: "Maulana Azad Education Foundation",
    provider_type: "Government",
    amount: 12000,
    deadline: "2025-10-15",
    course_levels: ["Class 9", "Class 10", "Class 11", "Class 12"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Female"],
    states: [],
    religions: ["Muslim", "Christian", "Sikh", "Buddhist", "Parsi", "Jain"],
    min_percentage: 50,
    description:
      "Exclusively for minority girl students studying in Class 9–12. Named after Begum Hazrat Mahal, recognizing meritorious minority girls nationwide.",
    documents_required: ["Aadhaar Card", "Minority Community Certificate", "Previous Marksheet", "Bank Passbook"],
    apply_url: "https://maef.nic.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: [],
    emoji: "👩",
  },
  {
    id: "sch-013",
    name: "Sitaram Jindal Foundation Scholarship",
    provider: "Sitaram Jindal Foundation",
    provider_type: "NGO",
    amount: 30000,
    deadline: "2025-08-31",
    course_levels: ["Class 11", "Class 12", "UG", "PG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 55,
    description:
      "Merit-cum-means scholarship for students across all streams. Special consideration for first-generation learners and rural students.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Previous Marksheet", "Bank Passbook", "College ID"],
    apply_url: "https://sitaramjindalfoundation.org",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Commerce", "Arts", "Science"],
    emoji: "🌟",
  },
  {
    id: "sch-014",
    name: "CSIR-UGC NET JRF Fellowship",
    provider: "Council of Scientific & Industrial Research",
    provider_type: "Government",
    amount: 360000,
    deadline: "2025-12-31",
    course_levels: ["PhD"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: null,
    description:
      "Junior Research Fellowship for PhD students in Life Sciences, Physical Sciences, Chemical Sciences, Mathematical Sciences, and Earth Sciences. ₹31,000/month + HRA.",
    documents_required: ["Aadhaar Card", "NET/JRF Certificate", "College ID", "Bank Passbook"],
    apply_url: "https://csirhrdg.res.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Pure Sciences", "Research", "STEM"],
    emoji: "🧪",
  },
  {
    id: "sch-015",
    name: "Narotam Sekhsaria Foundation Scholarship",
    provider: "Narotam Sekhsaria Foundation",
    provider_type: "NGO",
    amount: 400000,
    deadline: "2025-07-31",
    course_levels: ["PG", "PhD"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: null,
    description:
      "Prestigious scholarship for postgraduate and PhD studies abroad (USA, UK, Australia, Canada). Covers tuition, living, travel. Mentorship from industry leaders.",
    documents_required: ["Aadhaar Card", "Undergraduate Degree", "Admission Letter", "Bank Passbook", "SOP / Essay"],
    apply_url: "https://nsfindia.org",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Arts", "Law", "Social Sciences"],
    emoji: "🌍",
  },
  {
    id: "sch-016",
    name: "Vidyasaarathi Scholarship",
    provider: "NSDL e-Governance Infrastructure",
    provider_type: "Corporate",
    amount: 40000,
    deadline: "2025-09-30",
    course_levels: ["UG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 60,
    description:
      "Technology-driven scholarship platform offering multiple scholarships from various corporate providers. Single application, multiple opportunities.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 12 Marksheet", "College ID", "Bank Passbook"],
    apply_url: "https://www.vidyasaarathi.co.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Commerce", "Science"],
    emoji: "💻",
  },
  {
    id: "sch-017",
    name: "Pragati Scholarship for Girls (AICTE)",
    provider: "AICTE",
    provider_type: "Government",
    amount: 50000,
    deadline: "2025-10-31",
    course_levels: ["UG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Female"],
    states: [],
    religions: [],
    min_percentage: null,
    description:
      "Encouraging girls to pursue technical education. ₹30,000 tuition + ₹20,000 incidentals per year for two daughters per family in AICTE-approved institutions.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 12 Marksheet", "College ID", "Bank Passbook"],
    apply_url: "https://aicte-india.org/pragati",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Technical"],
    emoji: "👩‍💻",
  },
  {
    id: "sch-018",
    name: "Ishan Uday Scholarship for NE Region",
    provider: "UGC (Ministry of Education)",
    provider_type: "Government",
    amount: 54000,
    deadline: "2025-10-31",
    course_levels: ["UG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: ["Arunachal Pradesh","Assam","Manipur","Meghalaya","Mizoram","Nagaland","Sikkim","Tripura"],
    religions: [],
    min_percentage: null,
    description:
      "Special scholarship for students from North-East Indian states. Covers general degree courses and professional courses. Monthly stipend of ₹5,400 (day scholars) or ₹7,800 (hostellers).",
    documents_required: ["Aadhaar Card", "Domicile Certificate", "Class 12 Marksheet", "College ID", "Bank Passbook"],
    apply_url: "https://scholarships.gov.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Engineering", "Medical", "Commerce", "Arts", "Science"],
    emoji: "🏔️",
  },
  {
    id: "sch-019",
    name: "Maulana Azad National Fellowship",
    provider: "Ministry of Minority Affairs",
    provider_type: "Government",
    amount: 200000,
    deadline: "2025-11-30",
    course_levels: ["PhD"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: ["Muslim", "Christian", "Sikh", "Buddhist", "Parsi", "Jain"],
    min_percentage: null,
    description:
      "Integrated five-year fellowship for minority community PhD students. Covers all expenses including JRF (₹31,000/month) and SRF phases. UGC-NET mandatory.",
    documents_required: ["Aadhaar Card", "Minority Certificate", "NET/JRF Certificate", "College ID", "Bank Passbook"],
    apply_url: "https://scholarships.gov.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: ["Research", "Pure Sciences", "Arts", "Humanities"],
    emoji: "📚",
  },
  {
    id: "sch-020",
    name: "NMMS Scholarship (Class 8→9)",
    provider: "Ministry of Education, Govt. of India",
    provider_type: "Government",
    amount: 12000,
    deadline: "2025-09-15",
    course_levels: ["Class 9"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    genders: ["Any"],
    states: [],
    religions: [],
    min_percentage: 55,
    description:
      "National Means-cum-Merit Scholarship for Class 9 students from government schools. ₹1,000/month to retain meritorious economically weaker section students in school.",
    documents_required: ["Aadhaar Card", "Income Certificate", "Class 8 Marksheet", "Bank Passbook"],
    apply_url: "https://scholarships.gov.in",
    is_featured: false,
    created_at: "2025-01-01T00:00:00Z",
    field_tags: [],
    emoji: "📖",
  },
];

// Helper: format Indian currency
export function formatINR(amount: number): string {
  if (amount >= 100000) {
    const lakhs = amount / 100000;
    return `₹${lakhs % 1 === 0 ? lakhs.toFixed(0) : lakhs.toFixed(1)}L`;
  }
  if (amount >= 1000) {
    const thousands = amount / 1000;
    return `₹${thousands % 1 === 0 ? thousands.toFixed(0) : thousands.toFixed(1)}K`;
  }
  return `₹${amount.toLocaleString("en-IN")}`;
}

export function formatINRFull(amount: number): string {
  return "₹" + amount.toLocaleString("en-IN");
}

// Helper: format deadline
export function formatDeadline(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
}

// Helper: days until deadline
export function daysUntil(dateStr: string): number {
  const now = new Date();
  const d = new Date(dateStr);
  return Math.ceil((d.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}
